name: Atualizar Contribution Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "27 3 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar repositório
        uses: actions/checkout@v4

      - name: Preparar pasta
        run: mkdir -p assets/snake

      - name: Gerar cobrinha das contribuições
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake/github-snake-dark.svg?color_snake=#A855F7&color_dots=#30363D,#414B5A,#312E81,#6D28D9,#A855F7
            assets/snake/github-snake-light.svg?color_snake=#7C3AED&color_dots=#E5E7EB,#DDD6FE,#C4B5FD,#8B5CF6,#7C3AED
      - name: Salvar atualização
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add assets/snake/*.svg
          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
          else
            git commit -m "chore: update contribution snake [skip ci]"
            git push
          fi
